name: Make rpm

on:
  workflow_dispatch:
  push:
    paths:
    - '!.github/**'

jobs:
  rpm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    container:
      image: ghcr.io/simonpintarelli/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_HW: CPUS=2
      options: --cpus 2 --privileged

    steps:
      - uses: actions/checkout@v3
      - run: |
          make rpm
          sudo rpmbuild --rebuild "$(find rpm/SRPMS -name '*.rpm' -type f -print -quit)" --define "_topdir $(pwd)/rpm"
          sudo rpm --install "$(find rpm/RPMS -name '*.rpm' -type f -print -quit)"
          find rpm -name '*.rpm' -type f -exec cp {} . \;

      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: slurm-uenv-mount-${{ matrix.version }}
          tag_name: slurm-uenv-mount-${{ matrix.version }}
          files: |
            *.rpm
