name: Build Testing Container Package

on:
  workflow_dispatch:
  push:
    paths:
    - '!.github/**'

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    env:
      base_tag:     ghcr.io/simonpintarelli/slurm-container-${{ matrix.version }}:latest
      cache_tag:    ghcr.io/simonpintarelli/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build tester image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ci/Dockerfile
        push: true
        tags: ${{ env.cache_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args:
          DOCKER_CONTAINER=${{ env.base_tag }}

  build-plugin:
    needs: build-test-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    container:
      image: ghcr.io/simonpintarelli/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_HW: CPUS=2
      options: --cpus 2 --privileged

    steps:
      - uses: actions/checkout@v3
      - run:
          make install
      - run:
          echo "required /usr/lib64/libslurm-uenv-mount.so" > /etc/slurm/plugstack.conf
      - run: |
          /entrypoint.sh
          sinfo
          # setup /home/testuser/fs.sqfs, /home/testuser/fs2.sqfs
          ci/create-dummy-sqfs.sh
      - run: |
          su testuser -c sh <<\EOF
          sbatch --wait ci/tests/test.sbatch
          EOF
      - run: |
          su testuser -c sh <<\EOF
          ci/tests/squashfs-run.sh
          EOF
