name: VersionChecker

on:
  push:
    tags:
      - 'v*'

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Version check
      id: check
      run: |
           VERSION="v$(cat VERSION)"
           GIT_VERSION=$(git describe --tags)
           if [ "$VERSION" != "$GIT_VERSION" ]; then
             echo ::set-output name=VERSION_ISSUE::yes
             echo ::set-output name=VERSION::$VERSION
             echo ::set-output name=GIT_VERSION::$GIT_VERSION
           fi
    - uses: JasonEtco/create-an-issue@v2.4.0
      if: steps.check.outputs.VERSION_ISSUE == 'yes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CMAKE_VERSION: ${{ steps.check.outputs.VERSION }}
        GIT_VERSION: ${{ steps.check.outputs.GIT_VERSION }}
      with:
        filename: .github/tag-issue.md
